from typing import Dict, List

import torch

def get_nccl_unique_id() -> List[int]: ...

class RNCCLcomm:
    def __init__(self, unique_id: List[int], world_size: int, total_rank: int): ...
    def nccl_group_start(self) -> None: ...
    def nccl_group_end(self) -> None: ...
    def nccl_send(data: torch.Tensor, peer: int) -> None: ...
    def nccl_recv(data: torch.Tensor, peer: int) -> None: ...
